# Generated by Django 5.2.5 on 2025-08-11 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', '⭐ Low'), ('medium', '⭐⭐ Medium'), ('high', '⭐⭐⭐ High')], default='medium', max_length=10),
        ),
    ]
